# Generated by Django 3.2.4 on 2021-06-20 09:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=42)),
                ('email', models.EmailField(max_length=120, null=True)),
                ('birthdate', models.DateField()),
                ('enroll_date', models.DateField(default=datetime.date.today)),
                ('graduate_date', models.DateField(default=datetime.date.today)),
                ('graduate_date2', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
